### PR TITLE
Go routine in TestContractRequestHandler

### PR DESCRIPTION
**Pull request by HarryL5004**
Issue #325

### CODE REVIEW

**Comment by kstola2** [comment]
What happened to using WaitGroup?

**Comment by HarryL5004** [comment]
If waitgroup is used in `cmd main.go`, the waitgroup counter can go negative and panic.

**Comment by kstola2** [comment]
Why would we news one in main.go? The issue just concerns the test function.

**Comment by HarryL5004** [comment]
That's because a wait group instance must be passed into the contract handler to signal the waitgroup that this goroutine is done, and main.go initiate a contract handler.

**Comment by kstola2** [comment]
Hm. Can you do something like 

```
var waitgroup sync.WaitGroup
waitgroup.Add(1)
go func(){
    handler.ServeHTTP(rr, tt.req)
    waitgroup.Done()
}()
waitgroup.Wait()
```

**Comment by kstola2** [comment]
I don't think it's a great idea to edit so many files for this issue, I'd almost rather just have the 1 second sleep at that point. But there's gotta be a way to use a WaitGroup to achieve this.

**Comment by kstola2** [comment]
Interesting, do you know why increasing the cap makes it work? I'm curious

**Comment by HarryL5004** [comment]
Previously the channel blocks all processes until there's a receiver retrieving the contract in the channel. By increasing the capacity, the channel will only start to block processes when it is full. If the channel is never full, it will block any processes.

**Pull request merged**
