### PR TITLE
Added Command Line Arg Test

### PR DESCRIPTION
**Pull request by jldistefano**

### CODE REVIEW

**Comment by jldistefano** [comment]
I've updated the branch

**Comment by kstola2** [comment]
Everything looks fine however I found a package that already does all this lol:

https://godoc.org/github.com/pborman/getopt

It also supports short and long flags (like `-t` vs `--test`). What do you think?

**Comment by jldistefano** [comment]
Honestly I'd rather implement it manually, I could add support for short and long flags as well. I intended to complete this one myself, unless you think it would be a good Friday one.

**Comment by kstola2** [comment]
Okay. For the readcmdlineargs test, I don't understand the situation where that function should return an error though

**Comment by jldistefano** [comment]
If it recieves an empty input line, it should return an error. This wouldn't normally be possible during normal stdin operation, but because it has the ability to simulate input, that case is required.

**Comment by kstola2** [comment]
If it'll never be possible with stdin then that test seems unnecessary and all tests should assume you have at least one arg I think.

**Comment by jldistefano** [comment]
I could change it to only return the queue and assume that there is one argument and thus no errors, but since the function will only be used internally inside of the ProcessCmdAgs function, I don't think there's any harm in keeping it in.

**Comment by kstola2** [comment]
If the function is going to be called inside the other always wouldnt it be better to combine them? Since you're not returning an error from the first one

**Comment by kstola2** [comment]
If the first one just grabs the arguments you could use the getopt package for that part and then issue could be making sure you're pushing processing the arguments and the test could be focused around handling valid args

**Pull request merged**
