### PR TITLE
Added GenerateNRandomKeys()

### PR DESCRIPTION
**Pull request by jldistefano**
Issue #145

### CODE REVIEW

**Comment by kstola2** [comment]
For some reason Travis is screaming

**Comment by kstola2** [comment]
image
Apparently this is another project structure issue. Can you investigate this?

**Comment by jldistefano** [comment]
The package is called `testfunctions` not `test_functions`, I'm not sure why travis thinks its the latter.

**Comment by kstola2** [comment]
Maybe test is some sort of wildcard for a specific golang functionality. We can change all the names to something like `airdropsim` instead of `test...`

**Comment by jldistefano** [comment]
How can I look at the full error messages?

**Comment by arosso3** [comment]
you have `test_functions` in the imports for main.go

image

**Comment by kstola2** [comment]
@jldistefano there's links to travis in this PR

**Pull request merged**
