### PR TITLE
Issue #47) Added WorkLoop Signal Handler

### PR DESCRIPTION
**Pull request by jldistefano**

### CODE REVIEW

**Comment by kstola2** [comment]
I added a carriage return so the `^C` doesn't get printed. Did you intentionally add a newline character at the end of the log statement? Just wondering.

**Comment by jldistefano** [comment]
I didn't notice, but i used Println() with a \n at the end. So I guess it would print two new lines.

**Comment by kstola2** [comment]
Also, I think the log statement should go inside the work loop function, since we're going to be printing out log statements in there as well. The loop might terminate for other reasons, not always an interrupt. Maybe we should pass the logger in as an argument to `WorkLoop`

**Comment by kstola2** [comment]
Made the changes. Let me know what you think

**Comment by jldistefano** [comment]
It works well

**Comment by kstola2** [comment]
I'm working on using it as an argument instead of the current way it's working

**Comment by kstola2** [comment]
This might cause some merge conflicts with dev, but I think it's a lot cleaner. What do you think?

**Comment by jldistefano** [comment]
Runs good for me

**Pull request merged**
