### PR TITLE
Respond to RequestWalletInfo & UpdateWallet

### PR DESCRIPTION
**Pull request by kstola2**
Issues #216  and #214

### CODE REVIEW

**Comment by kstola2** [comment]
Okay, I'm probably going to split this into two separate PR's, I'll do that tomorrow.

**Comment by HarryL5004** [comment]
`67: conn, err := ln.Accept()` in `cmd/producer/main.go`
`ln` is `nil` when the package test is running the test for `ResponseToAcc...`, hence the nil pointer error.
Running the test by itself is fine though...

**Comment by HarryL5004** [comment]
` 265: ln, err := net.Listen("tcp", "localhost:9001")`
Changing the port seems to fix the problem..

**Comment by kstola2** [comment]
I think it's cause the goroutines are persisting after each test function concludes. It would make sense that changing the port will make it work.

**Pull request merged**
