### PR TITLE
Endpoints

### PR DESCRIPTION
**Pull request by harshalpatel165**
added constant for in endpoint for incoming blocks

### CODE REVIEW

**Comment by kstola2** [comment]
So the problem here is you made a branch based off of `json_test`, and not `dev`

You need to make a branch based off of `dev`, make your changes, then push, then make a PR from that dev-based branch.

**Comment by harshalpatel165** [comment]
ok, I wasnt able to checkout from dev before(says I didnt permissions or something), but now that I created the endpoint branch, I can checkout to dev. So now that im on the dev branch, do I just create a new branch called endpoint or whatever.

**Comment by kstola2** [comment]
You weren't able to checkout `dev` before because you had uncommitted changes. For future reference, a dirty trick is to run `git stash`, which will remove the changes that are uncommitted and cache them so that you can call `git stash pop` on in a different branch.

If you are able to checkout the `dev` branch now, follow the original sequence of steps I showed in the other PR, add your changes, push, and make a PR from that new branch.

**Comment by harshalpatel165** [comment]
you want me to make a pull request from the new branch to which branch?

**Comment by kstola2** [comment]
> you want me to make a pull request from the new branch to which branch? back to dev im assuming?

I think you can change the source branch on this PR. If you can't then just make a separate PR.

**Comment by harshalpatel165** [comment]
so whats the base branch, and the compare branch is the new branch that I make?

**Comment by kstola2** [comment]
It should be `dev` < `yourNewBranch`

**Comment by harshalpatel165** [comment]
ok thats what it shows for this one

**Comment by kstola2** [comment]
Yeah you need to make a new branch based off `dev`. The `endpoints` branch you have here is based on `json_test`.

**Pull request closed without merging**
