### PR TITLE
RecoverMetadata support for Account balance Table

### PR DESCRIPTION
**Pull request by HarryL5004**
Issue #176

### CODE REVIEW

**Comment by kstola2** [comment]
I have a question: I looked over your code, I'm wondering if the case where the two tables already exist, would calling `Recover...` overwrite them? or would it simply do nothing if it detected them?

**Comment by HarryL5004** [comment]
If the tables already exist, calling `Recover...` will empty the files containing the tables and recover metadata starting from the beginning.

**Comment by kstola2** [comment]
So it will basically overwrite them if they already exist? Cause that would be correct

**Comment by HarryL5004** [comment]
Yea, it should overwrite them if the tables already exist.

**Comment by kstola2** [comment]
@HarryL5004 Update: I put issue #189 up, so that will complicate things less hopefully. You can assume that the []Data field of each block you extract will have serializied contracts, so no more data headers and bodies.

**Comment by kstola2** [comment]
@HarryL5004 Looks good, however because of issue #189 we're going to be replacing the `Data` struct for now (might use it again in a version 2, so that code wasn't all for nothing). This means that these tests and code will need to be tweaked a bit. I'm going to ask that someone finish up that issue so we can knock this one out.

**Pull request merged**
