### PR TITLE
moved tests and its main

### PR DESCRIPTION
**Pull request by ramirez915**
moved the tests and the main found in the same original test directory into internal/producer. I hope this is what was asked to do

### CODE REVIEW

**Comment by kstola2** [comment]
This PR is failing on travis...

**Comment by kstola2** [comment]
Did you make your branch based on `dev`?

**Comment by ramirez915** [comment]
I think I did make it off of the dev branch. I used the github gui and I think i did choose dev when making the new branch... is there a way to start fresh with what the dev branch has on this branch or would it be easier to just delete this branch and just redo it?

**Comment by ramirez915** [comment]
I made a change that caused an issue, hopefully that helps

**Pull request merged**
