### PR TITLE
added unit test for LoadJSON

### PR DESCRIPTION
**Pull request by harshalpatel165**
#318  I added unit test for LoadJSON

### CODE REVIEW

**Comment by harshalpatel165** [comment]
> Hey harshal. Can you make the endpoint changes on a new separate branch? We typically restrict each PR to one issue.

I was about to ask, how do I go about doing that.

**Comment by kstola2** [comment]
> > Hey harshal. Can you make the endpoint changes on a new separate branch? We typically restrict each PR to one issue.
> 
> I was about to ask, how do I go about doing that. I noticed that I went to the jsontest branch and im not sure why

First step is to go to your local repo, checkout the `dev` branch, then make a new branch called whatever you want.

so if you're in the project root on your machine, and you're using Windows if I recall, you'd be in gitbash, run the following:

`git branch` -> should output your current branch name, which should be `json_test`
`git checkout dev` -> should switch to the `dev` branch on your machine
`git checkout -b someNewBranchName` -> will create a new branch and switch to it.

**Comment by harshalpatel165** [comment]
> > > Hey harshal. Can you make the endpoint changes on a new separate branch? We typically restrict each PR to one issue.
> > 
> > 
> > I was about to ask, how do I go about doing that. I noticed that I went to the jsontest branch and im not sure why
> 
> First step is to go to your local repo, checkout the `dev` branch, then make a new branch called whatever you want.
> 
> so if you're in the project root on your machine, and you're using Windows if I recall, you'd be in gitbash, run the following:
> 
> `git branch` -> should output your current branch name, which should be `json_test`
> `git checkout dev` -> should switch to the `dev` branch on your machine
> `git checkout -b someNewBranchName` -> will create a new branch and switch to it.

git branch says im currently in endpoints branch. when I try and checkout to dev branch, it gives me the error---
 Your local changes to the following files would be overwritten by checkout:
        internal/endpoints/endpoints.go
Please commit your changes or stash them before you switch branches.
Aborting

**Comment by kstola2** [comment]
> > > > Hey harshal. Can you make the endpoint changes on a new separate branch? We typically restrict each PR to one issue.
> > > 
> > > 
> > > I was about to ask, how do I go about doing that. I noticed that I went to the jsontest branch and im not sure why
> > 
> > 
> > First step is to go to your local repo, checkout the `dev` branch, then make a new branch called whatever you want.
> > so if you're in the project root on your machine, and you're using Windows if I recall, you'd be in gitbash, run the following:
> > `git branch` -> should output your current branch name, which should be `json_test`
> > `git checkout dev` -> should switch to the `dev` branch on your machine
> > `git checkout -b someNewBranchName` -> will create a new branch and switch to it.
> 
> git branch says im currently in endpoints branch. when I try and checkout to dev branch, it gives me the error---
> Your local changes to the following files would be overwritten by checkout:
> internal/endpoints/endpoints.go
> Please commit your changes or stash them before you switch branches.
> Aborting

what is the result of `git branch`

**Comment by harshalpatel165** [comment]
> > > Hey harshal. Can you make the endpoint changes on a new separate branch? We typically restrict each PR to one issue.
> > 
> > 
> > I was about to ask, how do I go about doing that. I noticed that I went to the jsontest branch and im not sure why
> 
> First step is to go to your local repo, checkout the `dev` branch, then make a new branch called whatever you want.
> 
> so if you're in the project root on your machine, and you're using Windows if I recall, you'd be in gitbash, run the following:
> 
> `git branch` -> should output your current branch name, which should be `json_test`
> `git checkout dev` -> should switch to the `dev` branch on your machine
> `git checkout -b someNewBranchName` -> will create a new branch and switch to it.

git branch says im currently in endpoints branch. when I try and checkout to dev branch, it gives me the error---
 Your local changes to the following files would be overwritten by checkout:
        internal/endpoints/endpoints.go
Please commit your changes or stash them before you switch branches.
Aborting


> > > > > Hey harshal. Can you make the endpoint changes on a new separate branch? We typically restrict each PR to one issue.
> > > > 
> > > > 
> > > > I was about to ask, how do I go about doing that. I noticed that I went to the jsontest branch and im not sure why
> > > 
> > > 
> > > First step is to go to your local repo, checkout the `dev` branch, then make a new branch called whatever you want.
> > > so if you're in the project root on your machine, and you're using Windows if I recall, you'd be in gitbash, run the following:
> > > `git branch` -> should output your current branch name, which should be `json_test`
> > > `git checkout dev` -> should switch to the `dev` branch on your machine
> > > `git checkout -b someNewBranchName` -> will create a new branch and switch to it.
> > 
> > 
> > git branch says im currently in endpoints branch. when I try and checkout to dev branch, it gives me the error---
> > Your local changes to the following files would be overwritten by checkout:
> > internal/endpoints/endpoints.go
> > Please commit your changes or stash them before you switch branches.
> > Aborting
> 
> what is the result of `git branch`
* endpoints
  harsh
  json_test
  master
  practice-git

**Comment by kstola2** [comment]
Make a PR with `dev < `endpoints`  then

**Pull request merged**
