### PR TITLE
Finished up handler test

### PR DESCRIPTION
**Pull request by kstola2**
Issue #1 Task 3

Handler test should run smoothly.

### CODE REVIEW

**Comment by jldistefano** [comment]
The test file works for me, though the use of relative import paths concerns me. Because of the way that go's hyperspecific directory tree works, I was only able to run file inside the directory they are contained in.
This can be fixed by replacing any relative import paths with paths from go/src, though it forces you to assume that project_aurum is directly inside of src. An example of this would be instead of `../producer/src` assuming you are in producer, `project_aurum/producer/src` allows this to be run from anywhere, provided project_aurum is directly inside of go/src.

**Comment by Vineet77** [comment]
Yeah, we could go from relative imports to imports from the GO_PATH. It might be better, since then, all people would need to do is go get, to get our modules.

**Comment by kstola2** [comment]
Will need to restructure this branch's directories per PR #19

**Comment by kstola2** [comment]
Made new PR.

**Pull request closed without merging**
