### PR TITLE
Update block.go

### PR DESCRIPTION
**Pull request by Csando6**
added recursion and appending elements, need to add hashing method

### CODE REVIEW

**Comment by Csando6** [comment]
Thanks for the help!
Ill look into bit manipulations and queue in go

**Comment by kstola2** [comment]
I don't think you'll need to use bit manipulations, but definitely check out the Deque double ended que package.

**Comment by Csando6** [comment]
I have been trying to search for a built in deque package by go, but could not find it. I was able to find a deque packages written by others. 

Should we implement others deque, implement my own deque, or did I miss something.

Thanks,
Charly S

**Comment by kstola2** [comment]
@Csando6 So you can either implement your own deque or import the [deque package ](https://godoc.org/gopkg.in/karalabe/cookiejar.v1/collections/deque).

[This ](https://stackoverflow.com/questions/2818852/is-there-a-queue-implementation) may be helpful if you want to implement it on your own.

Also, Issue #20 is almost completed, once it is, pull the changes from that so you can use that hashing function for your issue. I'll let you know when it's ready.

**Comment by kstola2** [comment]
@Csando6 , good news the `HashSHA256` function has been merged into dev so you can now use it. Message me on slack if you want more real-time support for this issue. Make sure you either merge the changes from dev into this PR's branch or make a new PR after your changes are completed.

**Comment by kstola2** [comment]
Closing this PR due to the corresponding issue being completed.

**Pull request closed without merging**
