### PR TITLE
Remake AccountInfo struct

### PR DESCRIPTION
**Pull request by ktrufin**
#368 
Wallet Address: af7af87547aa15955cfa99d43bde53ea6ba928784408b27b7a3d6eaed2889ddf

### CODE REVIEW

**Comment by kstola2** [comment]
I believe it's failing because you have some imports in the `producer` test file that are unused. This will cause a build failure in go.

**Comment by kstola2** [comment]
Gonna close this for now

**Comment by ktrufin** [comment]
Wallet Address: af7af87547aa15955cfa99d43bde53ea6ba928784408b27b7a3d6eaed2889ddf

**Comment by ktrufin** [comment]
#368

**Comment by bashbashbash** [comment]
Since there hasn't been much movement on this PR or issue, I will close and open it back up to whomever wants to take it

**Pull request closed without merging**
