### PR TITLE
Update block.go

### PR DESCRIPTION
**Pull request by Csando6**
adding recursion and element appending, still need to implement hashing

### CODE REVIEW

**Comment by kstola2** [comment]
This is a pull request to master please set it to dev.

**Comment by kstola2** [comment]
Hey so there are merge conflicts here, Can you pull from dev to your branch, then add in your code? Another option is to resolve them manually but I don't know if you know how to do that.

**Comment by Csando6** [comment]
Should I fork the project, apply changes, then pull request.
Sorry, lacking experience

**Comment by kstola2** [comment]
Make a new branch based on dev, then copy paste your changes into that branch where applicable. Then make a PR from that branch to dev, making sure you're only selecting `block.go` and `block_test.go`

**Pull request closed without merging**
