### PR TITLE
Created Master Test Script

### PR DESCRIPTION
**Pull request by arosso3**
#12

### CODE REVIEW

**Comment by arosso3** [comment]
Where are you running the script from where the output stays on the screen? When I run it w/o the input line at the end it just closes the console after running.

**Comment by kstola2** [comment]
I'm using the bash terminal in vscode. It also works if I run it in Ubuntu for Windows.

**Comment by arosso3** [comment]
That makes sense. I've just been running it from file explorer.

**Comment by kstola2** [comment]
Try it in a terminal

**Comment by arosso3** [comment]
Unless I missed something in my testing the script should work now if you open it either directly from file explorer or from a terminal with `./run_all_tests.sh`

**Comment by arosso3** [comment]
Tested it on both windows and Linux

**Comment by jldistefano** [comment]
Actually now that I think about it, its kind of strange that its running main files at all.

**Comment by kstola2** [comment]
You could also do something like "if package does not have name main -> run test"

**Pull request merged**
